sudo: required
notifications:
  email: false
services:
- docker
language: python
python:
- 3.6
git:
  depth: false
script:
- echo "building images"
- make build
- make push
deploy:
- provider: script
  skip_cleanup: true
  script: bash .travis-deploy.sh
  on:
    branch: master
env:
  global:
  - secure: s+3CrR3sBP3euh9FPwZ7zTgtm5HHlnuiGesWZ/nKfs4/QpXOg1VWuBRrsyTJA53iZIqEhHtAypwUGxz985KVaRaXeeTocNQCtOm0joW0Ee+NnVlCOWH4QD3lMgwlxCr9b9r0TNAsMnAS3lqgDRSeKulQ2TVWADRAK4YCS2SkoRk3YpcC++6hqkcG8cw00Yuw2LwdZSB8UfydoeY9tUyCktNp2veBgcwQ+M40GGjIfEjMxWo+jx4i5BOTKk0DumBp3oytVK++cRNeg1ZG3yOdbCgZHfB6agOKTFZT32HuinSKLujgfLQ8Map4czNmUGIwmwgnj2/6jNhR3yCeDF4VW1I3D+nojmb5BSInuwplScU6vUdmTqXZNXqTa/hqC26mhZ6FjB2iZecNduikjeChlDbcG2P7gWZCOn+zeg1y8UT8QOtWpkIX/30vfvYkne0GSPGqyRgjMuPd0dAO0uOkX79nc6XD+oOOKz8UbcFbyqmF0X39sXctb7/bgQ8d11JvFZQSCLVD+rj79oRccd9pir36o27AjtfksBdmNUYBqzTzDWSuG6Ic1+S01QJ+X6deaoQJS+9LuekomOSBFXNvpnnx3jifATFm4SVX7IsGG2/+dS9R2nxCHh6lfKXBFzLmijXJ5yk89CLo9Auyp0aynqE6k+E04vstPoWImWUvE6I=
  - secure: G6yohMmyIqwo1Q80pm6HERY0RWrij0s5b1tam0AAD31AUHhkSYPcm6CC8Hk07rUvdeqAfBih/2Jgjvq8ik2XtGjbaWtcYxa4OAEjzZ7i98o0xoBBF/91U35OqhUaz109uVNdt5FdeEqGMpfuwMwz5UGTc5bQAFRHttmT0myuppubaM3m0ucC3lRHS6kcTeKiH0tMs+E4vG3tKKa3NGF5rqLQoAJWNpcvpBlBzZJGM4MvyjViNjMBgsroLe56kkdRlc8iRCi1XfTIUsWPfst7gwezIuzABkaRkk9y/ow46ELTzBONaCUhEP/Y5KDq3Opu5TphQ7X9fzqDIE+mIE77hXkYF/OWoaZ5piX2S3BA799eMER+b1xq4MmBPpbZBs8OeJe9SjPXrrh2yW+yhrffTdpxDMS0Zes1YF8MXofejCAeup4/jcR7L33SwPLidDN5JI4bginMC11LVQ2VZwa3DXSeoeHBLavntTXMqH7i+zp8KlJnKgd/PTXjfK9DA+S40LSZUsXC/jgqmmxOJ/N3VNAH5KD1x1QYvARpRkxlmkX/SveoNvQSocOvnFrizaASAcqdVivbjxu5csMartz25XsejqqBBtvFP7TKHDwTH2XpIat2pql0Abt2i0W0sKlq7yaHlbzoEX1m5hTGPDycGSsBSbPwZcBz+HeQGtvro/8=
