sudo: required
notifications:
  email: false
services:
- docker
language: python
python:
- 3.6
git:
  depth: false
script:
- echo "building images"
- make build
- make push
deploy:
- provider: script
  skip_cleanup: true
  script: bash .travis-deploy.sh
  on:
    branch: master
env:
  global:
  - secure: LS7rLc6fr++dZAPGjyKB95nwiaF/CNYkhlGBfgIWQwHNN7Y8lAsGu1895Urpb3re0C7BHQTqGnzV1wMnJXSsu6z3iJUMRyfuAsOpIzcUNpoM67u0pb0H7hI0jcFQC97qLOmBtyXOaJbMKCx6sV2hk8JkRczxU3vUgHBBkpjnEY5Le5xzNatQuaOrX48t+YwJmOKizSl0+n6ksxDk3f7n7oOEVhGF0sUrW1Y+C+JdXkeFm+bQ8dtFuURL53OkOOKzzRl7KjAin97QVcxNqSGJZFoPe402ibJ0bkfe7SnPWhotWh5tywDJD+gc297/2HaTfmUntppxZc94/jBgtx9LgK9ocjG7ZmZv1fD7uqHK8HuUWhBXscGns406zrNXuWve9gK1ibLvMPrnLKNev6OQ161GhuL2LyyTed5+D5iK2Ph6mJTKhnmgsccWgoY00mYq+n/4HObHoNk3f2xmRlAXwYf+Jm2YXvR19KCfzDlpuGT3uYh1JVfPTYnojSBqMd+uitjbKjbUClgx/nvhc7JduXbq+xeS9JZI9nBg8648MXTizMr2imYxKDa9lKvJhkM36KyUc4ubjD29UtuNwbI5ihqLBusFe5zz1im0mYaDf93UV7a3ktkCd+v2tgeRlwIxYqNqm9ass5d01RbMNzkzmV5UVZhfhnfLwokifVf6RjU=
  - secure: kM+xS5PLUm/H5F1vPzrCkgV7DABR73RLRXLXOis9aSdVn5mhR4TQEGsvAKc3hpIKTz83rcSl0P6qN85P9nzZKk8ZJgQf6qnl8j5Rim4EWHgf3dtyfn9iP4QujlulmgGuv8xGAOCbgSCW6OTgyXIznEs5hBdylIliz3rKbKmv9TyM94hLVsX+/fhc3yDmkkxyRBJPqfOxvNqO4Icm4WOLMX1EN9/BdhK+dClbqFDRR3zIJMgDb2tH0vJ+ObYtwaLTbVb64LKlFo9Xl+Ty3I9YCb12cFAGn7VVY+RAQU8FJFA0trQQN90qxJRuIGTA6L9zDLHxY2dgrkALQKtgdxaKhXahIMPicH2XlgKgIK2EfEvlr8dVDOnAbXNkvrDxW3tA9r7kvcmZkatptIfLwnSM079u3dWnFBKhsypecKJzU/Awkgd4ojWvonxs2+SwXHww9RkbIkAlttSCRGbbuj/189nvbuiRmGq6aM6PvqdIbzX+bMVlnB4EtFhuKWe6RVQnd3xPZwIrmeAVw+REvvq51C7d5td1AzL5WGjv8jjCcp8hNxZQOKTfw0LXSmZi0mUFlXK00a6x6habj2E7rvql2eK9BsZ8Hemb91pP7EsTxcNQIt6hpMXJWZ3bGmMQTb2YfZI+EsnrzvLfQauQ+/IGIKvjXEqjMakON0kyc0TcdQM=
  - secure: HP8Wn5G4hwHvZG0PjEHtMA+nHJPrfzcshVP9zumpb+Yg4qYAiZa9KK/l/m13JC1Dbt7KX11XXMmyLwarnuA1z5XeiNOHSTmy2LSgLZL5ZtxmufRtWnGHLgW26V3tJwH35V/ARydvh+7AeQWrOEec99HqFgpg0PwvTQmLf3OlrNlYoatidsQPi9LxVcBZFwxGDFa939q6CbM93JKJVXUEkxkxviIq2bGPnZykrTv8KGHZm7g/KGfZGKunDtI7Cky99t50gWfy0xUQGgjlaAanIpgEnrH8wlhZHPwQ+VssHev57tmuKcMnucDhp1SP4NkOOREaUzAzR7F5ThJXeOi1BlCVVslvnmz0PRccidyUQBOXdLVpV3VhowK9X1tHYQc9M4g1oZ3lmux5tVFh6MMx6AUOpheWvdTsHxkV5zcBkFgAMHAezZzNQtE5WOaeKO1VPPUjbEeqj7vLlv09xljuf9gootSk/bpX1gY/rO+zqcafhr5j/zYFFSRXI6yVaH6h0V86jz6ilkvD5HGhKVhom8LUoaPI0Ctd0EN2Gtr56e9wwuR5Uz2g4P4KKRJL5+etwoK5A2GpyDEcHRWazjxWyfuwUxN6/XtjEg1/ra+5EjGdW+gGKV2JdLKXnsHGKNj77om3lYT0m5mxiZmxx98XPRlDmwlyco9FIPsWIgyX/mA=
